### ISSUE TITLE
Tests fail with v0.8.9

### ISSUE THREAD

**Issue by justin-lau** [switchfly/ember-mocha#71] opened 2016-02-01 03:59 UTC
With the following logs:

```
not ok 1 PhantomJS 1.9 - Global error: SyntaxError: Parse error at http://localhost:7357/assets/test-support.js, line 7347
    ---
        Log: |
            { type: 'error',
              text: 'SyntaxError: Parse error at http://localhost:7357/assets/test-support.js, line 7347\n' }
    ...
not ok 2 PhantomJS 1.9 - Global error: ReferenceError: Can't find variable: blanket at http://localhost:7357/assets/blanket-options.js, line 30
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: blanket at http://localhost:7357/assets/blanket-options.js, line 30\n' }
    ...
not ok 3 PhantomJS 1.9 - Global error: ReferenceError: Can't find variable: blanket at http://localhost:7357/assets/blanket-loader.js, line 4
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: blanket at http://localhost:7357/assets/blanket-loader.js, line 4\n' }
    ...
not ok 4 PhantomJS 1.9 - Global error: Error: Could not find module `ember-mocha` imported from `emedia-esmc/tests/test-helper` at http://localhost:7357/assets/vendor.js, line 180
    ---
        Log: |
            { type: 'error',
              text: 'Error: Could not find module `ember-mocha` imported from `emedia-esmc/tests/test-helper` at http://localhost:7357/assets/vendor.js, line 180\n' }
    ...
not ok 5 PhantomJS 1.9 - Global error: ReferenceError: Can't find variable: blanket at http://localhost:7357/assets/test-loader.js, line 119
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: blanket at http://localhost:7357/assets/test-loader.js, line 119\n' }
    ...
not ok 6 PhantomJS 1.9 - Global error: Error: Assertion Failed: The tests file was not loaded. Make sure your tests index.html includes "assets/tests.js". at http://localhost:7357/assets/vendor.js, line 16840
    ---
        Log: |
            { type: 'error',
              text: 'Error: Assertion Failed: The tests file was not loaded. Make sure your tests index.html includes "assets/tests.js". at http://localhost:7357/assets/vendor.js, line 16840\n' }
    ...
```

**Comment by sly7-7** [comment] 2016-02-01 11:17
I encounter the same. Locking to the previous version (0.8.8) is the workaround for now.
@rwjblue So it seems to be related to the update of ember-test-helpers (this looks like the only difference between the two last releases). 
The root error here seems to be that it cannot find the module 'ember-mocha'. I don't know how to go further

**Comment by rwjblue** [comment] 2016-02-01 12:45
Can someone put together a demo repo that I can test with?

**Comment by sly7-7** [comment] 2016-02-01 13:24
@rwjblue it's here: https://github.com/sly7-7/ember-mocha-bug

It's just an empty new app, with ember-cli-mocha installed.

launch ember test and the error is:

```
not ok 1 PhantomJS 2.0 - Global error: SyntaxError: Unexpected token '(' at http://localhost:7357/assets/test-support.js, line 2048
    ---
        Log: |
            { type: 'error',
              text: 'SyntaxError: Unexpected token \'(\' at http://localhost:7357/assets/test-support.js, line 2048\n' }
    ...
not ok 2 PhantomJS 2.0 - Global error: Error: Could not find module `ember-mocha` imported from `ember-mocha-bug/tests/test-helper` at http://localhost:7357/assets/vendor.js, line 173
    ---
        Log: |
            { type: 'error',
              text: 'Error: Could not find module `ember-mocha` imported from `ember-mocha-bug/tests/test-helper` at http://localhost:7357/assets/vendor.js, line 173\n' }
    ...
not ok 3 PhantomJS 2.0 - Global error: Error: Assertion Failed: The tests file was not loaded. Make sure your tests index.html includes "assets/tests.js". at http://localhost:7357/assets/vendor.js, line 15692
    ---
        Log: |
            { type: 'error',
              text: 'Error: Assertion Failed: The tests file was not loaded. Make sure your tests index.html includes "assets/tests.js". at http://localhost:7357/assets/vendor.js, line 15692\n' }
    ...
```

**Comment by sly7-7** [comment] 2016-02-01 13:33
This line https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/test-module-for-acceptance.js#L19 is throwing `Uncaught SyntaxError: Unexpected token {`

Is this a compiler compatibilty problem, or something like that ?

**Comment by rwjblue** [comment] 2016-02-01 13:37
Most likely this is not being babel transpiled properly.  I'm digging into it now...

**Comment by mupkoo** [comment] 2016-02-01 13:42
@rwjblue I think this is the problem as well.

This is from the `bower_components/ember-mocha/ember-mocha.js`

```js
// ...
      let { Application, config } = this.callbacks;
      let application;

      Ember['default'].run(() => {
        application = Application.create(config);
        application.setupForTesting();
        application.injectTestHelpers();
      });
// ...
```

**Comment by rwjblue** [comment] 2016-02-01 13:47
Yep, I had made some changes to the ember-qunit build pipeline to allow us to use ember-test-helpers internally, but I forgot that I hadn't also updated the ember-mocha pipeline.  

I'm working on updating right now, and will hopefully have a 0.8.10 published in the next hour or so....

**Comment by rwjblue** [comment] 2016-02-01 14:35
Released 0.8.10 with the corrections from #72. I'll reopen this until someone can confirm that things are working properly again...

**Comment by pavloo** [comment] 2016-02-01 14:51
@rwjblue I had problems with an update from `0.8.8` to `0.8.9` (my `ember test` command simply hanged after `Built project successfully.`). But with `0.8.10` everything works fine :+1:

**Comment by rwjblue** [comment] 2016-02-01 14:53
Awesome, thanks for confirming @pavloo.  I also confirmed with @sly7-7 in slack.  

Closing this, sorry for all the troubles y'all!

**Closed by rwjblue** 2016-02-01 14:53 UTC

**Comment by justin-lau** [comment] 2016-02-02 03:37
Thanks for the good work guys!

**Comment by Turbo87** [comment] 2016-02-11 11:21
I seem to have a similar issue with `0.8.11`:

```
not ok 1 PhantomJS 2.1 - Global error: ReferenceError: Can't find variable: define at http://localhost:7357/assets/tests.js, line 1
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: define at http://localhost:7357/assets/tests.js, line 1\n' }
    ...
not ok 2 PhantomJS 2.1 - Global error: ReferenceError: Can't find variable: define at http://localhost:7357/assets/test-loader.js, line 3
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: define at http://localhost:7357/assets/test-loader.js, line 3\n' }
    ...
not ok 3 PhantomJS 2.1 - Global error: ReferenceError: Can't find variable: EmberENV at http://localhost:7357/6451/tests/index.html?hidepassed, line 39
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: EmberENV at http://localhost:7357/6451/tests/index.html?hidepassed, line 39\n' }
    ...
```

Unfortunately it's not reproducible and only happens sometimes causing the CI to randomly fail. if I restart the CI build it usually works fine again.

**Comment by rwjblue** [comment] 2016-02-11 12:57
@turbo87 - I believe that is related to an issue opened recently in ember-cli.

**Comment by Turbo87** [comment] 2016-02-11 13:13
@rwjblue I'm using `1.13.15` of ember-cli if that matters

**Comment by tavosansal** [comment] 2016-06-27 20:10
@Turbo87 Did you ever resolve your issue? I am running into this as well.

**Comment by Turbo87** [comment] 2016-06-27 20:30
@tavosansal I don't remember... 🙈    but I'm using `ember-cli-mocha` on a current project so in general it works fine.
